#!/bin/bash

source /etc/rdy/strings/STRINGS

modules_list=/etc/rdy/modules/tools/list_modules.rdy
path="/etc/rdy/modules/tools/"


if [ ! -f $modules_list ]; then
touch $modules_list
fi

number=$(wc -l $modules_list)
numberlist=$(echo "$number" |awk -F " " '{print $1}')


add_module(){
echo
echo -e "${DIVIS}";
echo -e "${yellow} ADICIONAR NOVO MÓDULO ${none}";
echo
echo -e "${cyan} NOME DO MÓDULO SEM ESPAÇOS ${none}";
read -p ">>> " modulename
echo 
echo -e "${cyan} LINK DE DOWNLOAD ${none}";
read -p ">>> " modulelink
echo
echo -e "${green} Será criada uma pasta com o nome do módulo (${magenta}${modulename}${none}${green}) e o módulo, baixado através do link, será salvo nessa pasta, o arquivo será renomeado para o nome definido ${none}";
echo -ne "${white}//${yellow}//${green}//${mag}//    ${green}Pressione uma tecla para continuar, ou CTRL+C para cancelar$f"; read -n1 -r -p "";
echo
if [ ! -d ${path}$modulename ]
then
mkdir -p ${path}$modulename
fi
if test -f "${path}$modulename/$modulename"; then

rm ${path}$modulename/${modulename}*

fi

echo $modulename >> $modules_list
wget -cO - $modulelink > ${path}$modulename/$modulename 1> /dev/null 2> /dev/null
chmod 711 ${path}$modulename/$modulename
echo -e "${green} $OK ${none}";

bash ${path}tools

}


menu(){
echo -e "${DIVIS}"; 
echo -e "${yellow} FERRAMENTAS ${none}";
echo -e "${DIVIS}"; 
echo -e "${blue} [add]${green} /> ${yellow} ADICIONAR MÓDULO$f";
nl -w2 -s " /> " $modules_list
echo "";
echo -ne "$cyano Opção [1 - $numberlist, ${red}0 exit${cyano}] $f"; read -p "/> " option

if [[ "$option" = 'add' ]] || [[ "$option" = 'ADD' ]] || [[ "$option" = 'help' ]] || [[ "$option" = 'ajuda' ]] || [[ "$option" = '0' ]] || [[ "$option" = 'exit' ]] || [[ "$option" = 'EXIT' ]]; then

case $option in
add | ADD) add_module ;;
help | ajuda) help ;;
00 | 0 | exit | EXIT) exit ;;
 *)echo -e "$cred Opção inválida!$f" ; echo "" ; sleep 2 ; ${path}tools;;
   esac

else
command=$(sed -n ${option}p $modules_list)
bash ${path}$command/$command
fi
}

menu